(in-package :matrix-framework)

;;; what i want is a timeline, to be then printed like so:
;;; timestamp user: message

(defun display-room-events-list (list-of-formatted-events)
  (loop for event in list-of-formatted-events
     do
       (princ event)
       (terpri)
       (princ "--------------------------------------------------------------------------------")
       (terpri)))

(defun get-events-from-timeline (timeline)
  (let ((events (assoc "events" (rest timeline) :test #'string=)))
    events))

(defun parse-timeline-events (list-of-events)
  "takes a list of events, and returns a list of strings, one for each event, 
that are ready to be displayed. 

currently only the m.room.message types of messages are working"
  (when (stringp (car list-of-events))
    (setf list-of-events (rest list-of-events)))
  (mapcar #'parse-single-event list-of-events))

(defun parse-single-event (event)
  "takes in one event, and returns that event formatted and ready for displaying. 
it also updates the room, based on the 'unsigned' portion of the event. this means
side effects, as its calling a function that will change some data. "
  (let ((unsigned (cdr (assoc "unsigned" event :test #'string=)))
	(type (cdr (assoc "type" event :test #'string=))))
    ;; (update-room unsigned) ;; this should check for 'replaces_state' among others and update the room to reflect any changes.
    (cond ((string= type "m.room.message")
	   (format-message-event event))
	  ((string= type "m.room.member")
	   (format-member-event event))
	  (t
	   "this message type has not been implemented"))))

(defun format-member-event (event)
  "takes in an event of type m.room.member and formats it, returning the formatted text"
  (let* ((sender (cdr (assoc "sender" event :test #'string=)))
	 (content (cdr (assoc "content" event :test #'string=)))
	 (member? (cdr (assoc "membership" content :test #'string=))))
    (if (string= member? "leave") ;; theres only leave/join possible
	(format nil "~A has left the room" sender)
	(format nil "~A (~A) has joined the room"
		(cdr (assoc "displayname" content :test #'string=)) sender))))

(defun format-message-event (event)
  "takes in one event that is of type m.room.message and formats it, returning the formatted
text. "
  (let ((sender (cdr (assoc "sender" event :test #'string=)))
	(text (let ((content (cdr (assoc "content" event :test #'string=))))
		(when (string= "m.text" (cdr (assoc "msgtype" content :test #'string=)))
		  (cdr (assoc "body" content :test #'string=))))))
    (format nil "~a says:~%    ~a" sender text)))

("timeline" ("limited" . T)
    ("prev_batch"
     . "t61403-744420923_612504091_785461_198007165_91480693_514921_13191467_10132383_24004")
    ("events"
     (("unsigned" ("age" . 14746183)
       ("replaces_state" . "$154232048530NTrgb:asagi.moe")
       ("prev_sender" . "@lucy:asagi.moe")
       ("prev_content" ("membership" . "join") ("displayname" . "Lucy")
        ("avatar_url")))
      ("type" . "m.room.member") ("state_key" . "@lucy:asagi.moe")
      ("sender" . "@lucy:asagi.moe") ("origin_server_ts" . 1542392994843)
      ("membership" . "leave") ("event_id" . "$154239299460kzmwI:asagi.moe")
      ("content" ("membership" . "leave")))
     (("unsigned" ("age" . 13816784)
       ("prev_sender" . "@freenode_mart_k:matrix.org")
       ("prev_content" ("membership" . "join") ("displayname" . "mart_k")
        ("avatar_url"))
       ("replaces_state" . "$15423861072061619taCtI:matrix.org"))
      ("type" . "m.room.member") ("state_key" . "@freenode_mart_k:matrix.org")
      ("sender" . "@freenode_mart_k:matrix.org")
      ("origin_server_ts" . 1542393924242) ("membership" . "leave")
      ("event_id" . "$15423939242162922YxPLF:matrix.org")
      ("content" ("membership" . "leave")))
     (("unsigned" ("age" . 12645046)) ("type" . "m.room.message")
      ("sender" . "@pdadroidmx:matrix.org")
      ("origin_server_ts" . 1542395095980)
      ("event_id" . "$1542395095660525WBEoL:matrix.org")
      ("content" ("msgtype" . "m.text") ("body" . ";)")))
     (("unsigned" ("age" . 12611606)
       ("replaces_state" . "$15423892241mgOlp:chat.eastman.tech")
       ("prev_sender" . "@andrew:chat.eastman.tech")
       ("prev_content" ("membership" . "join") ("displayname" . "andrew")
        ("avatar_url")))
      ("type" . "m.room.member") ("state_key" . "@andrew:chat.eastman.tech")
      ("sender" . "@andrew:chat.eastman.tech")
      ("origin_server_ts" . 1542395129420) ("membership" . "leave")
      ("event_id" . "$1542395129144gJJjt:chat.eastman.tech")
      ("content" ("membership" . "leave")))
     (("unsigned" ("age" . 11819945)
       ("prev_sender" . "@freenode_Chiku:matrix.org")
       ("prev_content" ("membership" . "join") ("displayname" . "Chiku")
        ("avatar_url"))
       ("replaces_state" . "$15423864302066105rUtTT:matrix.org"))
      ("type" . "m.room.member") ("state_key" . "@freenode_Chiku:matrix.org")
      ("sender" . "@freenode_Chiku:matrix.org")
      ("origin_server_ts" . 1542395921081) ("membership" . "leave")
      ("event_id" . "$15423959212187041fLvTt:matrix.org")
      ("content" ("membership" . "leave")))
     (("unsigned" ("age" . 11683633)
       ("prev_sender" . "@freenode_tlaxkit:matrix.org")
       ("prev_content" ("membership" . "leave"))
       ("replaces_state" . "$15400810221822899mSckR:matrix.org"))
      ("type" . "m.room.member") ("state_key" . "@freenode_tlaxkit:matrix.org")
      ("sender" . "@freenode_tlaxkit:matrix.org")
      ("origin_server_ts" . 1542396057393) ("membership" . "join")
      ("event_id" . "$15423960572188635dTWoX:matrix.org")
      ("content" ("membership" . "join") ("displayname" . "tlaxkit")
       ("avatar_url")))
     (("unsigned" ("age" . 6860701)
       ("prev_sender" . "@freenode_AkemiHomura:matrix.org")
       ("prev_content" ("membership" . "join") ("displayname" . "AkemiHomura")
        ("avatar_url"))
       ("replaces_state" . "$15421767335156177wpXoD:matrix.org"))
      ("type" . "m.room.member")
      ("state_key" . "@freenode_AkemiHomura:matrix.org")
      ("sender" . "@freenode_AkemiHomura:matrix.org")
      ("origin_server_ts" . 1542400880325) ("membership" . "leave")
      ("event_id" . "$15424008802245987qBWHi:matrix.org")
      ("content" ("membership" . "leave")))
     (("unsigned" ("age" . 6292168)
       ("prev_sender" . "@freenode_AkemiHomura:matrix.org")
       ("prev_content" ("membership" . "leave"))
       ("replaces_state" . "$15424008802245987qBWHi:matrix.org"))
      ("type" . "m.room.member")
      ("state_key" . "@freenode_AkemiHomura:matrix.org")
      ("sender" . "@freenode_AkemiHomura:matrix.org")
      ("origin_server_ts" . 1542401448858) ("membership" . "join")
      ("event_id" . "$15424014482252875JQpSi:matrix.org")
      ("content" ("membership" . "join") ("displayname" . "AkemiHomura")
       ("avatar_url")))
     (("unsigned" ("age" . 6063327)
       ("prev_sender" . "@freenode_tlaxkit:matrix.org")
       ("prev_content" ("membership" . "join") ("displayname" . "tlaxkit")
        ("avatar_url"))
       ("replaces_state" . "$15423960572188635dTWoX:matrix.org"))
      ("type" . "m.room.member") ("state_key" . "@freenode_tlaxkit:matrix.org")
      ("sender" . "@freenode_tlaxkit:matrix.org")
      ("origin_server_ts" . 1542401677699) ("membership" . "leave")
      ("event_id" . "$15424016772255901NFMEq:matrix.org")
      ("content" ("membership" . "leave")))
     (("unsigned" ("age" . 961829)
       ("prev_sender" . "@freenode_feigned:matrix.org")
       ("prev_content" ("displayname" . "feigned (IRC)") ("avatar_url")
        ("membership" . "join"))
       ("replaces_state" . "$153908221458118CGcKC:matrix.org"))
      ("type" . "m.room.member") ("state_key" . "@freenode_feigned:matrix.org")
      ("sender" . "@freenode_feigned:matrix.org")
      ("origin_server_ts" . 1542406779197) ("membership" . "leave")
      ("event_id" . "$15424067792316312ednYb:matrix.org")
      ("content" ("membership" . "leave")))))
